GestionImpresoras/Models/Marca.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GestionImpresoras.Models
{
    [Table("Marca")]
    public class Marca
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        public String Nombre { get; set; }

        [StringLength(200)]
        public string Descripcion { get; set; }
        public List<Modelo> Modelos { get; set; }

    }
}

GestionImpresoras/Controllers/MarcasController.cs
using GestionImpresoras.Data;
using GestionImpresoras.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GestionImpresoras.Controllers
{
    public class MarcasController : Controller
    {
        private readonly ApplicationDBContext _contexto;

        public MarcasController(ApplicationDBContext contexto)
        {
            this._contexto = contexto;
        }

        [HttpGet]
        //  Codigo para la vista index con la tabla  
        public async Task<IActionResult> Index()
        {
            //Codigo utilizando merge de codigo Hector de Leon, FG, R2W
            var listado = await _contexto.Marcas.OrderBy(m => m.Nombre).ToListAsync();
            return View(listado);
        }

        [HttpGet]
        // Codigo para Get y SelectListItem de FG
        public async Task<ActionResult<List<Marca>>> Get()
        {
            var listado = await _contexto.Marcas.ToListAsync();
            return listado;
        }


        [HttpGet("{marcaId}/modelo")]
        // Codigo FG  para listado de Modelos en vistas Blazor
        public async Task<List<Modelo>> GetEstados(int marcaId)
        {
            return  await _contexto.Modelos.Where(m => m.MarcaId == marcaId).OrderBy(m => m.Nombre).ToListAsync();
        }

        [HttpGet]
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Crear(Marca marca)
        {
            if (ModelState.IsValid)
            {
                _contexto.Marcas.Add(marca);
                await _contexto.SaveChangesAsync();
                return RedirectToAction("Index");    // RedirectToAction(nameof(Index))
            }
            return View();
        }

        [HttpGet]
        public IActionResult Editar(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Noencontrado", "Home");
            }
            else
            {
                var marca = _contexto.Marcas.Find(id);
                if (marca == null)
                {
                    return RedirectToAction("Noencontrado", "Home");
                }
                return View(marca);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(Marca marca)
        {
            if (ModelState.IsValid)
            {
                _contexto.Marcas.Update(marca);
                await _contexto.SaveChangesAsync();
                return RedirectToAction(nameof(Index));    //  RedirectToAction("Index")
            }
            return View();
        }

        [HttpGet]
        public IActionResult Borrar(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Noencontrado", "Home");
            }
            else
            {
                var marca = _contexto.Marcas.Find(id);
                if (marca == null)
                {
                    return RedirectToAction("Noencontrado", "Home");
                }
                return View(marca);
            }
        }

        [HttpPost, ActionName("Borrar")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BorrarMarca(int? id)
        {
            var marca = await _contexto.Marcas.FindAsync(id);
            if (marca == null)
            {
                return View();
            }
            else _contexto.Marcas.Remove(marca);
            await _contexto.SaveChangesAsync();
            return RedirectToAction(nameof(Index));    //  RedirectToAction("Index")
        }

        [HttpGet]
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Noencontrado", "Home");
            }
            else
            {
                var contacto = _contexto.Marcas.Find(id);
                if (contacto == null)
                {
                    return RedirectToAction("Noencontrado", "Home");
                }
                return View(contacto);
            }
        }
    }
}

GestionImpresoras/Views/Marcas/Borrar.cshtml
@using GestionImpresoras.Models;
@model Marca
@{
    ViewData["Title"] = "Borrar Marca";
}
<h1>Borrar Marca</h1>
<h3>¿Estás seguro de que deseas borrar esta Marca?</h3>
<hr />
<form asp-controller="Marcas" asp-action="Borrar" method="post">
    <!-- Definir el id que se envía desde la vista al controlador -->
    <input type="hidden" asp-for="Id" value="@Model.Id" class="Marca" />
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="mb-3">
        <label asp-for="Nombre" class="form-label">Nombre</label>
        <input type="text" asp-for="Nombre" class="form-control" readonly />
        <!-- Utilizo la opción readonly para no permitir cambiar el contenido de los campos -->
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Descripcion" class="form-label">Descripcion</label>
        <input type="text" asp-for="Descripcion" class="form-control" readonly />
        <span asp-validation-for="Descripcion" class="text-danger"></span>
    </div>
    <!---------------  Botones summit y cancelar  ------------->
    <button type="submit" class="btn btn-primary"><i class="bi bi-eraser"></i> Borrar</button>
    <a class="btn btn-secondary" asp-action="Index"><i class="bi bi-x-square"></i> Cancelar</i></a>
</form>

GestionImpresoras/Views/Marcas/Crear.cshtml
@model Marca

@{
    ViewData["Title"] = "Crear Marcas de Impresoras";
}


<h1>Crear Marca</h1>
<h5>Se refiere a las marcas de las impresoras </h5>
<hr />
    <form asp-action="Crear" asp-controller="Marcas" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="mb-3">
        <label asp-for="Nombre" class="form-label">Nombre</label>
        <input type="text" asp-for="Nombre" class="form-control" placeholder="Ingresa el nombre de la Marca" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Descripcion" class="form-label">Descripcion</label>
        <input type="text" asp-for="Descripcion" class="form-control" placeholder="Ingresa la descripción de la Marca" />
        <span asp-validation-for="Descripcion" class="text-danger"></span>
    </div>  
    <!---------------  Botones summit y cancelar  ------------->
    <button type="submit" class="btn btn-primary"><i class="bi bi-check-square"></i> Aplicar</button>
    <a class="btn btn-secondary" asp-action="Index"><i class="bi bi-backspace"></i> Cancelar</a>

</form>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

GestionImpresoras/Views/Marcas/Details.cshtml
@using GestionImpresoras.Models;
@model Marca
@{
    ViewData["Title"] = "Detalle de la Marca";
}
<h1>Detalles de la Marca consultada</h1>
<hr />
<form asp-controller="Marcas" asp-action="Details">

    <!-- Definir el id que se envía desde la vista al controlador -->
    <input type="hidden" asp-for="Id" value="@Model.Id" class="Impresora" />
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

   <div class="mb-3">
        <label asp-for="Nombre" class="form-label">Nombre</label>
        <!-- Utilizo la opción readonly para no permitir cambiar el contenido de los campos -->
        <input type="text" asp-for="Nombre" class="form-control" readonly />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Descripcion" class="form-label">Descripcion</label>
        <input type="text" asp-for="Descripcion" class="form-control" readonly />
        <span asp-validation-for="Descripcion" class="text-danger"></span>
    </div>
    <!---------------  Boton  regresar  ------------->
    <a class="btn btn-secondary" asp-action="Index"><i class="bi bi-x-square"></i> Regresar</i></a>

</form>

GestionImpresoras/Views/Marcas/Editar.cshtml
@using GestionImpresoras.Models
@model Marca
@{
    ViewData["Title"] = "Editar Marcas de Impresoras";
}
<h1>Editar Marca</h1>
<hr />
    <form asp-action="Editar" asp-controller="Marcas" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="mb-3">
        <label asp-for="Nombre" class="form-label">Nombre</label>
        <input type="text" asp-for="Nombre" class="form-control" placeholder="Ingresa el nombre de la Marca" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Descripcion" class="form-label">Descripcion</label>
        <input type="text" asp-for="Descripcion" class="form-control" placeholder="Ingresa la descripción de la Marca" />
        <span asp-validation-for="Descripcion" class="text-danger"></span>
    </div>

    <!---------------  Botones summit y cancelar  ------------->
    <button type="submit" class="btn btn-primary"><i class="bi bi-check-square"></i> Aplicar</button>
    <a class="btn btn-secondary" asp-action="Index"><i class="bi bi-backspace"></i> Cancelar</a>

</form>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

GestionImpresoras/Views/Marcas/Index.cshtml
@using GestionImpresoras.Models
@model IEnumerable<Marca>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center">Listado de Marcas</h1>
<div class="row">
    <div class="offset-9 col-3 mb-3">
        <div class="float-right">
            <a asp-action="Crear" asp-controller="Marcas" class="btn btn-success d-block mx-auto btn-lg">
                <i class="bi bi-folder-plus mr-2"></i>&nbsp;&nbsp;Nueva Marca
            </a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card border">
            <div class="card-header">
                <h3><strong>Listado de  @Model.Count()  Marcas</strong></h3>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                @if (Model.Count() > 0) 
                {
                    <table class="table table-bordered" id="tablaEstados" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>@Html.DisplayNameFor(m => m.Nombre)</th>
                                <th>@Html.DisplayNameFor(m => m.Descripcion)</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(m => item.Nombre)</td>
                                    <td>@Html.DisplayFor(m => item.Descripcion)</td>
                                    <td>
                                        <a class="btn btn-primary" asp-action="Editar" asp-route-id="@item.Id">
                                            <i class="bi bi-pencil"></i> Editar
                                        </a>
                                        <a class="btn btn-info" asp-action="Details" asp-route-id="@item.Id">
                                            <i class="bi bi-info-circle"></i> Detalle
                                        </a>
                                        <a class="btn btn-danger" asp-action="Borrar" asp-route-id="@item.Id">
                                            <i class="bi bi-eraser"></i> Borrar
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
                else
                {
                    <p>No hay registros</p>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            //Llamar a datatable
            $('#tablaEstados').DataTable({
                language: {
                    "decimal": "",
                    "emptyTable": "No hay información",
                    "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
                    "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
                    "infoFiltered": "(Filtrado de _MAX_ total entradas)",
                    "infoPostFix": "",
                    "thousands": ",",
                    "lengthMenu": "Mostrar _MENU_ Entradas",
                    "loadingRecords": "Cargando...",
                    "processing": "Procesando...",
                    "search": "Buscar:",
                    "zeroRecords": "Sin resultados encontrados",
                    "paginate": {
                        "first": "Primero",
                        "last": "Ultimo",
                        "next": "Siguiente",
                        "previous": "Anterior"
                    }
                }
            });
        });
    </script>
}