GestionImpresoras/Models/Mantenimiento.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GestionImpresoras.Models
{
    [Table("Mantenimiento")]
    public class Mantenimiento
    {
        [Key]
        public int Id { get; set; }

        public int ImpresoraId { get; set; }
        [Display(Name = "Impresora")]
        public virtual Impresora Impresora { get; set; } = null!; //Perdonar el nulo? y Ademas propiedad de navegacion 

        public int EstadoMttoId { get; set; }
        [Display(Name = "Estado Mtto")]
        public virtual EstadoMtto EstadoMtto { get; set; } = null!; //Perdonar el nulo? y Ademas propiedad de navegacion 

        [Display(Name = "Fecha Sol.")]
        [Column(TypeName = "Date")]
        public DateTime? FechaSolicitud { get; set; }  //El signo ? en DateTime expresa que puede almacenar nulo 

        [Display(Name = "Fecha Mtto.")]
        [Column(TypeName = "Date")]
        public DateTime? FechaMantenimiento { get; set; }  //El signo ? en DateTime expresa que puede almacenar nulo 

        [Display(Name = "Es Local")]
        public bool EsLocal { get; set; }

    }
}

GestionImpresoras/Controllers/MantenimientosController.cs
using GestionImpresoras.Models;
using Microsoft.AspNetCore.Mvc;
using GestionImpresoras.Data;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using GestionImpresoras.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace GestionImpresoras.Controllers
{
    public class MantenimientosController : Controller
    {
        private readonly ApplicationDBContext _contexto;

        public MantenimientosController(ApplicationDBContext contexto)
        {
            this._contexto = contexto;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var listado = await _contexto.Mantenimientos
                .Include(e => e.EstadoMtto)
                .Include(i => i.Impresora)
                .ToListAsync();
            return View(listado);
        }

        [HttpGet]
        public async Task<IActionResult> Crear()
        {
            if (!await _contexto.Impresoras.AnyAsync())
            {
                ModelState.AddModelError(string.Empty, "La tabla de impresoras está vacía");
                return View();
            }
            if (!await _contexto.EstadoMttos.AnyAsync())
            {
                ModelState.AddModelError(string.Empty, "La tabla de estados está vacía");
                return View();
            }

            ViewBag.ImpresoraId = await _contexto.Impresoras.Select(i => new SelectListItem { Value = i.Id.ToString(), Text = i.CodigoActivoFijo }).ToListAsync();
            ViewBag.EstadoMttoId = await _contexto.EstadoMttos.Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.Nombre }).ToListAsync();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Crear(Mantenimiento mantenimiento)
        {
            if (ModelState.IsValid)
            {
                _contexto.Mantenimientos.Add(mantenimiento);
                await _contexto.SaveChangesAsync();
                return RedirectToAction("Index");    // RedirectToAction(nameof(Index))
            }
            return View();
        }

        //Endpoints para el Borrar registros
        [HttpGet]
        public IActionResult Editar(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Noencontrado", "Home");
            }
            else
            {
                var itemDisplay = _contexto.Mantenimientos.Find(id);
                if (itemDisplay == null)
                {
                    return RedirectToAction("Noencontrado", "Home");
                }
                return View(itemDisplay);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(Mantenimiento mantenimiento)
        {
            if (ModelState.IsValid)
            {
                _contexto.Mantenimientos.Update(mantenimiento);
                await _contexto.SaveChangesAsync();
                return RedirectToAction(nameof(Index));    //  RedirectToAction("Index")
            }
            return View();
        }
    }
}

GestionImpresoras/Views/Mantenimientos/Crear.cshtml
@using GestionImpresoras.Models;
@using GestionImpresoras.ViewModels;
@model Mantenimiento

@{
    ViewData["Title"] = "Crear nuevo Mantenimiento";
}
<h1>Crear Mantenimiento</h1>
<h5>Se refiere a los Mantenimiento que se realizan al equipo de impresión de la institución o arrendado</h5>
<hr />
<form asp-action="Crear" asp-controller="Mantenimientos" method="post">

    <!---  Para Lista de Impresoras   -->
    <div class="mb-3 form-group">
        <label asp-for="ImpresoraId" class="form-label">Impresora</label>
        <select class="form-select form-select sm" asp-for="ImpresoraId" asp-items="ViewBag.ImpresoraId">
            <option> --- Seleccionar Impresora --- </option>
        </select>
        <span asp-validation-for="ImpresoraId" class="text-danger"></span>
    </div>
    <!---  Para Lista de Estado Mantenimiento   -->
    <div class="mb-3 form-group">
        <label asp-for="EstadoMttoId" class="form-label">Estado</label>
        <select class="form-select form-select sm" asp-for="EstadoMttoId" asp-items="ViewBag.EstadoMttoId">
            <option> --- Seleccionar Estado --- </option>
        </select>
        <span asp-validation-for="EstadoMttoId" class="text-danger"></span>
    </div>

    <div class="mb-3 form-group">
        <label asp-for="FechaSolicitud" class="form-label">Fecha Solicitud</label>
        <input type="date" asp-for="FechaSolicitud" class="form-control" />
        <span asp-validation-for="FechaSolicitud" class="text-danger"></span>
    </div>
    <div class="mb-3 form-group">
        <label asp-for="FechaMantenimiento" class="form-label">Fecha Mantenimiento</label>
        <input type="date" asp-for="FechaMantenimiento" class="form-control" />
        <span asp-validation-for="FechaMantenimiento" class="text-danger"></span>
    </div>
    <div class="mb-3 form-group form-check">
        <label asp-for="EsLocal" class="form-check-label">¿Es Mantenimiento Local? <i class="bi bi-house-fill text-success"></i></label>
        <input type="checkbox" asp-for="EsLocal" class="form-check-input" />
        <span asp-validation-for="EsLocal" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary"><i class="bi bi-check-square"></i> Aplicar</button>
    <a class="btn btn-secondary" asp-action="Index"><i class="bi bi-x-square"></i> Cancelar</i></a>

</form>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

GestionImpresoras/Views/Mantenimientos/Index.cshtml
@using GestionImpresoras.Models
@model IEnumerable<Mantenimiento>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1 class="text-center">Listado de Mantenimientos</h1>
<div class="row">
    <div class="offset-9 col-3 mb-3">
        <div class="float-right">
            <a asp-action="Crear" asp-controller="Mantenimientos" class="btn btn-success d-block mx-auto btn-lg">
                <i class="bi bi-folder-plus mr-2"></i>&nbsp;&nbsp;Nuevo Mantenimiento
            </a>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card border">
            <div class="card-header">
                <h3><strong>Listado de @Model.Count() Mantenimientos</strong></h3>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                @if (Model.Count() > 0)
                {
                    <table class="table table-bordered" id="tablaMantenimientos" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>@Html.DisplayNameFor(m => m.Impresora)</th>
                                <th>@Html.DisplayNameFor(m => m.EstadoMtto)</th>
                                <th>@Html.DisplayNameFor(m => m.FechaSolicitud)</th>
                                <th>@Html.DisplayNameFor(m => m.FechaMantenimiento)</th>
                                <th>@Html.DisplayNameFor(m => m.EsLocal)</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.Impresora.CodigoActivoFijo</td>
                                    <td>@item.EstadoMtto.Nombre</td>
                                    <td>@item.FechaSolicitud?.ToString("dd/MM/yyyy")</td>
                                    <td>@item.FechaMantenimiento?.ToString("dd/MM/yyyy")</td>
                                    <td>                                      
                                        @if (item.EsLocal)
                                        {
                                            <i class="bi bi-house-fill text-success"></i>
                                        }
                                        else
                                        {
                                            <i class="bi bi-house-fill text-muted"></i>
                                        }
                                          @(item.EsLocal ? "Sí" : "No")
                                    </td>
                                    <td>
                                        <a class="btn btn-primary" asp-action="Editar" asp-route-id="@item.Id">
                                            <i class="bi bi-pencil"></i> Editar
                                        </a>
                                        <a class="btn btn-info" asp-action="Details" asp-route-id="@item.Id">
                                            <i class="bi bi-info-circle"></i> Detalle
                                        </a>
                                        <a class="btn btn-danger" asp-action="Borrar" asp-route-id="@item.Id">
                                            <i class="bi bi-eraser"></i> Borrar
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
                else
                {
                    <p>No hay registros</p>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts{
<script>
    $(document).ready(function () {
        //Llamar a datatable
        $('#tablaMantenimientos').DataTable({
            language: {
                "decimal": "",
                "emptyTable": "No hay información",
                "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
                "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
                "infoFiltered": "(Filtrado de _MAX_ total entradas)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Mostrar _MENU_ Entradas",
                "loadingRecords": "Cargando...",
                "processing": "Procesando...",
                "search": "Buscar:",
                "zeroRecords": "Sin resultados encontrados",
                "paginate": {
                    "first": "Primero",
                    "last": "Ultimo",
                    "next": "Siguiente",
                    "previous": "Anterior"
                }
            }
        });
    });
</script>
}