GestionImpresoras/Controllers/ColoresController.cs
using GestionImpresoras.Data;
using GestionImpresoras.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GestionImpresoras.Controllers
{
    public class ColoresController : Controller
    {
        private readonly ApplicationDBContext _contexto;

        public ColoresController(ApplicationDBContext contexto)
        {
            this._contexto = contexto;
        } 
            
        public async Task<IActionResult> Index()
        {
            var listado = await _contexto.Colores.ToListAsync();
            return View(listado);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Color color)
        {
            if (ModelState.IsValid)
            {
                _contexto.Colores.Add(color);
                await _contexto.SaveChangesAsync();
                return RedirectToAction("Index");    // RedirectToAction(nameof(Index))
            }
            return View();
        }

        //Endpoints para el Borrar registros
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Noencontrado", "Home");
            }
            else
            {
                var colorDisplay = _contexto.Colores.Find(id);
                if (colorDisplay == null)
                {
                    return RedirectToAction("Noencontrado", "Home");
                }
                return View(colorDisplay);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Color color)
        {
            if (ModelState.IsValid)
            {
                _contexto.Colores.Update(color);
                await _contexto.SaveChangesAsync();
                return RedirectToAction(nameof(Index));    //  RedirectToAction("Index")
            }
            return View();
        }
        //Endpoints para el Borrar registros
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Noencontrado", "Home");
            }
            else
            {
                var colorDisplay = _contexto.Colores.Find(id);
                if (colorDisplay == null)
                {
                    return RedirectToAction("Noencontrado", "Home");
                }
                return View(colorDisplay);
            }
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteColor(int? id)
        {
            var colorDisplay = await _contexto.Colores.FindAsync(id);
            if (colorDisplay == null)
            {
                return View();
            }
            else _contexto.Colores.Remove(colorDisplay);
            await _contexto.SaveChangesAsync();
            return RedirectToAction(nameof(Index));    //  RedirectToAction("Index")
        }
        //Endpoint para el desplegar (Details) de registros
        [HttpGet]
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Noencontrado", "Home");
            }
            else
            {
                var colorDisplay = _contexto.Colores.Find(id);
                if (colorDisplay == null)
                {
                    return RedirectToAction("Noencontrado", "Home");
                }
                return View(colorDisplay);
            }
        }
    }
}

GestionImpresoras/Views/Colores/Create.cshtml
@using (Html.BeginForm())
@model Color
@{
    ViewData["Title"] = "Crear Colores de Tinta";
}
<h1>Crear Color</h1>
<h5>Se refiere a los colores de las tintas para los diferentes modelos de impresora</h5>
<hr />
@Html.AntiForgeryToken()
<form asp-action="Create" asp-controller="Colores" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="mb-3">
        <label asp-for="Nombre" class="form-label">Nombre</label>
        <input type="text" asp-for="Nombre" class="form-control" placeholder="Ingresa el nombre del Color" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>

    <!---------------  Botones summit y cancelar  ------------->
    <button type="submit" class="btn btn-primary"><i class="bi bi-check-square"></i> Aplicar</button>
    <a class="btn btn-secondary" asp-action="Index"><i class="bi bi-x-octagon"></i> Cancelar</a>

</form>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

GestionImpresoras/Views/Colores/Delete.cshtml
@using GestionImpresoras.Models;
@model Color

@{
    ViewData["Title"] = "Borrar Color";
}

<h1>Borrar Color </h1>
<h3>¿Estás seguro de que deseas borrar este Color?</h3>
<h3>@Model.Nombre </h3>
<hr />
<form asp-controller="Colores" asp-action="Delete">

    <!-- Definir el id que se envía desde la vista al controlador -->
    <input type="hidden" asp-for="Id" value="@Model.Id" class="Colores" />
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="mb-3">
        <label asp-for="Nombre" class="form-label">Nombre</label>
        <input type="text" asp-for="Nombre" class="form-control" readonly />
        <!-- Utilizo la opción readonly para no permitir cambiar el contenido de los campos -->
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>
    <!---------------  Botones summit y cancelar  ------------->
    <button type="submit" class="btn btn-primary"><i class="bi bi-eraser"></i> Borrar</button>
    <a class="btn btn-secondary" asp-action="Index"><i class="bi bi-x-square"></i> Cancelar</i></a>
</form>

GestionImpresoras/Views/Colores/Details.cshtml
@using GestionImpresoras.Models;
@model Color
@{
    ViewData["Title"] = "Detalle de Color";
}
<h1>Detalles de Color consultado</h1>
<hr />
<form asp-controller="Estados" asp-action="Details">

    <!-- Definir el id que se envía desde la vista al controlador -->
    <input type="hidden" asp-for="Id" value="@Model.Id" class="Impresora" />
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="mb-3">
        <label asp-for="Nombre" class="form-label">Nombre</label>
        <input type="text" asp-for="Nombre" class="form-control" readonly />
        <!-- Utilizo la opción readonly para no permitir cambiar el contenido de los campos -->
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>

     <a class="btn btn-secondary" asp-action="Index"><i class="bi bi-x-square"></i> Regresar</a>

</form>

GestionImpresoras/Views/Colores/Edit.cshtml
@using GestionImpresoras.Models
@model Color
@{
    ViewData["Title"] = "Editar Colores para tóner de Impresoras";
}
<h1>Editar Color</h1>
<h3>@Model.Nombre</h3>
<hr />
<form asp-action="Edit" asp-controller="Colores" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="mb-3">
        <label asp-for="Nombre" class="form-label">Nombre</label>
        <input type="text" asp-for="Nombre" class="form-control" placeholder="Ingresa el nombre de Estado" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>

    <!---------------  Botones summit y cancelar  ------------->
    <button type="submit" class="btn btn-primary"><i class="bi bi-check-square"></i> Aplicar</button>
    <a class="btn btn-secondary" asp-action="Index"><i class="bi bi-backspace"></i> Cancelar</a>

</form>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

GestionImpresoras/Views/Colores/Index.cshtml
@using GestionImpresoras.Models
@model IEnumerable<Color>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1 class="text-center">Listado de Colores</h1>
<div class="row">
    <div class="offset-9 col-3 mb-3">
        <div class="float-right">
            <a asp-action="Create" asp-controller="Colores" class="btn btn-success d-block mx-auto btn-lg">
                <i class="bi bi-folder-plus mr-2"></i>&nbsp;&nbsp; Nuevo Color
            </a>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card border">
            <div class="card-header">
                <h3><strong>Listado de @Model.Count() Colores</strong></h3>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                @if (Model.Count() > 0)
                {
                    <table class="table table-bordered" id="tablaColores" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>@Html.DisplayNameFor(m => m.Nombre)</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(m => item.Nombre)</td>
                                    <td>
                                        <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.Id">
                                            <i class="bi bi-pencil"></i> Editar
                                        </a>
                                        <a class="btn btn-info" asp-action="Details" asp-route-id="@item.Id">
                                            <i class="bi bi-info-circle"></i> Detalle
                                        </a>
                                        <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">
                                            <i class="bi bi-eraser"></i> Borrar
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
                else
                {
                    <p>No hay registros</p>
                }
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script>
        $(document).ready(function () {
            //Llamar a datatable
            $('#tablaColores').DataTable({
                language: {
                    "decimal": "",
                    "emptyTable": "No hay información",
                    "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
                    "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
                    "infoFiltered": "(Filtrado de _MAX_ total entradas)",
                    "infoPostFix": "",
                    "thousands": ",",
                    "lengthMenu": "Mostrar _MENU_ Entradas",
                    "loadingRecords": "Cargando...",
                    "processing": "Procesando...",
                    "search": "Buscar:",
                    "zeroRecords": "Sin resultados encontrados",
                    "paginate": {
                        "first": "Primero",
                        "last": "Ultimo",
                        "next": "Siguiente",
                        "previous": "Anterior"
                    }
                }
            });
        });
    </script>
}