GestionImpresoras/Controllers/SolicitudesController.cs
using GestionImpresoras.Data;
using GestionImpresoras.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GestionImpresoras.Services;
using GestionImpresoras.DTOs;

namespace GestionImpresoras.Controllers
{
    public class SolicitudesController : Controller
    {
        private readonly ApplicationDBContext _contexto;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly EmailService _emailService;
        private readonly String folderSolicitudes = @"imagenes\solicitudes";

        public SolicitudesController(ApplicationDBContext contexto, IWebHostEnvironment webHostEnvironment, EmailService emailService)
        {
            this._contexto = contexto;
            this._webHostEnvironment = webHostEnvironment;
            this._emailService = emailService;
        }

        [HttpGet]
        // Acción para mostrar la vista Index
        public async Task<IActionResult> Index()
        {
            // Encontrar el valor máximo de EstadoSolicitud
            var estadoMaximo = await _contexto.EstadoSolicitudes
                .OrderByDescending(es => es.Orden)
                .FirstOrDefaultAsync();

            var lista = await _contexto.Solicitudes
                .Include(x => x.Impresora)
                .Include(x => x.Color)
                .Include(x => x.EstadoSolicitud)
                .Select(s => new SolicitudShowDTO
                {
                    Solicitud = s,
                    EnEstadoMaximo = s.EstadoSolicitud.Orden == estadoMaximo.Orden
                })
                .ToListAsync();

            return View(lista);
        }

        // Metodos GET POST Solicitudes Crear
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            if (!await _contexto.Impresoras.AnyAsync())
            {
                ModelState.AddModelError(string.Empty, "La tabla de marcas está vacía");
                return View();
            }
            if (!await _contexto.Colores.AnyAsync())
            {
                ModelState.AddModelError(string.Empty, "La tabla de modelos está vacía");
                return View();
            }
            if (!await _contexto.Medios.AnyAsync())
            {
                ModelState.AddModelError(string.Empty, "La tabla de áreas está vacía");
                return View();
            }
            if (!await _contexto.EstadoSolicitudes.AnyAsync())
            {
                ModelState.AddModelError(string.Empty, "La tabla de áreas está vacía");
                return View();
            }
            ///<!----------------------  Grupo de SelectListItems --------------------------->
            ViewBag.ImpresoraId = await _contexto.Impresoras.Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.CodigoActivoFijo }).ToListAsync();
            ViewBag.EstadoSolicitudId = await _contexto.EstadoSolicitudes.Select(m => new SelectListItem { Value = m.Id.ToString(), Text = m.Nombre }).ToListAsync();
            ViewBag.ColorId = await _contexto.Colores.Select(a => new SelectListItem { Value = a.Id.ToString(), Text = a.Nombre }).ToListAsync();
            ViewBag.MedioId = await _contexto.Medios.Select(a => new SelectListItem { Value = a.Id.ToString(), Text = a.Nombre }).ToListAsync();

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Solicitud solicitud)
        {
            if (ModelState.IsValid)
            {
                //  Capturo los archivos seleccionados 
                var archivos = HttpContext.Request.Form.Files;
                string rootPath = _webHostEnvironment.WebRootPath;
                // Verifica si se está cargando un archivo
                if (archivos.Count > 0)
                {
                    // Para verificar si el directorio existe  
                    var pathFullSolicitudes = System.IO.Path.Combine(rootPath, folderSolicitudes);
                    if (!Directory.Exists(pathFullSolicitudes))
                    {
                        Directory.CreateDirectory(pathFullSolicitudes);
                    }
                    // Almacena el archivo en el servidor
                    string fileName = Guid.NewGuid().ToString();
                    var extension = Path.GetExtension(archivos[0].FileName).ToLower(); ;
                    if (extension != ".png" && extension != ".jpg" && extension != ".jpeg")
                    {
                        return RedirectToAction("Noencontrado", "Home");
                    }
                    using (var fileStreams = new FileStream(Path.Combine(pathFullSolicitudes, fileName + extension), FileMode.Create))
                    {
                        await archivos[0].CopyToAsync(fileStreams);
                    }
                    String bslash = @"\";
                    solicitud.UrlImagen = bslash + folderSolicitudes + bslash + fileName + extension;
                    //solicitud.FechaSolicitud = DateTime.Now;
                }
                _contexto.Solicitudes.Add(solicitud);
                await _contexto.SaveChangesAsync();

                // Obtener la información para el correo
                var emailData = await GetEmailData(solicitud.Id);
                if (emailData != null)
                {
                    await _emailService.SendEmail("registro", solicitud, emailData);
                }

                return RedirectToAction(nameof(Index));
            }
            ///<!----------------------  Grupo de SelectListItems --------------------------->
            ViewBag.ImpresoraId = await _contexto.Impresoras.Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.CodigoActivoFijo }).ToListAsync();
            ViewBag.EstadoSolicitudId = await _contexto.EstadoSolicitudes.Select(m => new SelectListItem { Value = m.Id.ToString(), Text = m.Nombre }).ToListAsync();
            ViewBag.ColorId = await _contexto.Colores.Select(a => new SelectListItem { Value = a.Id.ToString(), Text = a.Nombre }).ToListAsync();
            ViewBag.MedioId = await _contexto.Medios.Select(a => new SelectListItem { Value = a.Id.ToString(), Text = a.Nombre }).ToListAsync();
            return View();
        }
        private async Task<EmailData> GetEmailData(int solicitudId)
        {
            var solicitud = await _contexto.Solicitudes
                .Include(x => x.Impresora)
                .Include(x => x.Color)
                .Include(x => x.EstadoSolicitud)
                .FirstOrDefaultAsync(x => x.Id == solicitudId);

            if (solicitud != null)
            {
                var emailData = new EmailData
                {
                    FechaSolicitud = solicitud.FechaSolicitud,
                    Solicitante = solicitud.Solicitante,
                    Correo = solicitud.Email,
                    ImpresoraCodigo = solicitud.Impresora.CodigoActivoFijo,
                    ColorNombre = solicitud.Color.Nombre,
                    EstadoSolicitudNombre = solicitud.EstadoSolicitud.Nombre
                };
                return emailData;
            }

            return null;
        }
        // ----------------->>>>>   Metodos GET POST Solicitudes Editar
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Noencontrado", "Home");
            }
            else
            {
                var itemDisplay = await _contexto.Solicitudes.FindAsync(id);
                if (itemDisplay == null)
                {
                    return RedirectToAction("Noencontrado", "Home");
                }
                else
                {
                    ///<!----------------------   Grupo de SelectListItems --------------------------->
                    ViewBag.ImpresoraId = await _contexto.Impresoras.Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.CodigoActivoFijo }).ToListAsync();
                    ViewBag.EstadoSolicitudId = await _contexto.EstadoSolicitudes.Select(m => new SelectListItem { Value = m.Id.ToString(), Text = m.Nombre }).ToListAsync();
                    ViewBag.ColorId = await _contexto.Colores.Select(a => new SelectListItem { Value = a.Id.ToString(), Text = a.Nombre }).ToListAsync();
                    ViewBag.MedioId = await _contexto.Medios.Select(a => new SelectListItem { Value = a.Id.ToString(), Text = a.Nombre }).ToListAsync();

                    return View(itemDisplay);
                }
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Solicitud solicitud)
        {
            if (ModelState.IsValid)
            {
                //  Capturo los archivos seleccionados 
                var archivos = HttpContext.Request.Form.Files;
                string rootPath = _webHostEnvironment.WebRootPath;
                string ToRemove = null;
                if (!String.IsNullOrEmpty(solicitud.UrlImagen))
                {
                    ToRemove = Path.Combine(rootPath, solicitud.UrlImagen);
                }
                // Verifica si se está cargando un archivo
                if (archivos.Count > 0)
                {
                    // Para verificar si el directorio existe  
                    var pathFullSolicitudes = System.IO.Path.Combine(rootPath, folderSolicitudes);
                    if (!Directory.Exists(pathFullSolicitudes))
                    {
                        Directory.CreateDirectory(pathFullSolicitudes);
                    }
                    // Almacena el archivo en el servidor
                    string fileName = Guid.NewGuid().ToString();
                    var extension = Path.GetExtension(archivos[0].FileName).ToLower(); ;

GestionImpresoras/Views/Solicitudes/Borrar.cshtml
@using (Html.BeginForm())
@using GestionImpresoras.Models;
@model Solicitud
@{
        ViewData["Title"] = "Borrar Solicitud";
}
<h1>Borrar Solicitud</h1>
<h3>¿Estás seguro de que deseas borrar esta Solicitud?</h3>
<hr />
@Html.AntiForgeryToken()
<input type="hidden" asp-for="Id" value="@Model.Id" class="Solicitud" />
<img class="rounded foat-left" hidden id="imagenToShow" alt="Imagen Seleccionada" />
<form asp-action="Borrar" asp-controller="Solicitudes" method="post" enctype="multipart/form-data">
    <!---  Para Lista de Impresoras   -->
    <div class="mb-3 form-group">
        <label asp-for="ImpresoraId" class="form-label">Impresora</label>
        <select class="form-select form-select sm" asp-for="ImpresoraId" asp-items="ViewBag.ImpresoraId" disabled>
            <option> --- Seleccionar Impresora --- </option>
        </select>
        <span asp-validation-for="ImpresoraId" class="text-danger"></span>
    </div>
    <!--- Para Solicitante   -->
    <div class="mb-3 form-group">
        <label asp-for="Solicitante" class="form-label">Solicitante</label>
        <input type="" asp-for="Solicitante" class="form-control" readonly />
        <span asp-validation-for="Solicitante" class="text-danger"></span>
    </div>
    <div class="row">
        <div class="col-md-6">
            <!--- Para Lista de Estado de Solicitud   -->
            <div class="mb-3 form-group">
                <label asp-for="EstadoSolicitudId" class="form-label">Estado</label>
                <select class="form-select form-select sm" asp-for="EstadoSolicitudId" asp-items="ViewBag.EstadoSolicitudId" disabled>
                    <option> --- Seleccionar Estado --- </option>
                </select>
                <span asp-validation-for="EstadoSolicitudId" class="text-danger"></span>
            </div>
            <!--- Para Lista de Color Solicitado   -->
            <div class="mb-3 form-group">
                <label asp-for="ColorId" class="form-label">Color</label>
                <select class="form-select form-select sm" asp-for="ColorId" asp-items="ViewBag.ColorId" disabled>
                    <option> --- Seleccionar Color --- </option>
                </select>
                <span asp-validation-for="ColorId" class="text-danger"></span>
            </div>
            <!---  Para Lista de Fecha de Solicitud   -->
            <div class="mb-3 form-group">
                <label asp-for="FechaSolicitud" class="form-label">Fecha Solicitud</label>
                <input type="date" asp-for="FechaSolicitud" class="form-control" readonly />
                <span asp-validation-for="FechaSolicitud" class="text-danger"></span>
            </div>
            <!--- Para Lista de Medio Solicitado   -->
            <div class="mb-3 form-group">
                <label asp-for="MedioId" class="form-label">Medio</label>
                <select class="form-select form-select sm" asp-for="MedioId" asp-items="ViewBag.MedioId" disabled>
                    <option> --- Seleccionar Color --- </option>
                </select>
                <span asp-validation-for="MedioId " class="text-danger"></span>
            </div>
            <!--- Sobre Imagenes de documentación  -->
            <div class="mb-3 form-group">
                <label asp-for="UrlImagen" class="form-label">Datos de la imagen</label>
                <input type="text" asp-for="UrlImagen" class="form-control" name="UrlImagen" id="UpImagen" readonly />
            </div>
        </div>
        @if (!string.IsNullOrEmpty(@Model.UrlImagen))
        {
            <div class="col-md-6 d-flex justify-content-center align-items-center">
                <div class="mb-3 form-group text-center" style="text-align: center;">
                    <div class="imagen-container text-center" style="border: 1px solid black; margin: auto;">
                        <img src="@Model.UrlImagen" alt="Imagen de soporte" class="imagen-soporte" style="margin: auto; width: 100%; height: 100%; object-fit: contain;" />
                    </div>

                </div>
            </div>
        }
    </div>
    <!--- Para Detalles  -->
    <div class="mb-3 form-group">
        <label asp-for="Detalle" class="form-label">Detalles de la solicitud</label>
        <input type="" asp-for="Detalle" class="form-control" readonly />
        <span asp-validation-for="Detalle" class="text-danger"></span>
    </div>
    <div class="mb-3 form-group">
        <label asp-for="Detalle" class="form-label">Detalles de la solicitud</label>
        <textarea asp-for="Detalle" class="form-control" id="detalle-input" readonly></textarea>
        <span asp-validation-for="Detalle" class="text-danger"></span>
    </div>

    <!---------------  Botones summit y cancelar  ------------->
    <button type="submit" class="btn btn-primary"><i class="bi bi-eraser"></i> Borrar</button>
    <a class="btn btn-secondary" asp-action="Index"><i class="bi bi-stop-circle"> Cancelar</i></a>
</form>
@section Scripts {
    @{
       await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
<style>
    .imagen-container {
        width: 400px;
        height: 400px;
        object-fit: contain;
        display: flex;
        justify-content: center !important;
        align-items: center !important;
    }

    .imagen-soporte {
        max-width: 100%;
        max-height: 100%;
        border-radius: 5px;
        border: 1px solid #bbb9b9;
    }
</style>
}

GestionImpresoras/Views/Solicitudes/ChangeStatus.cshtml
@model GestionImpresoras.Models.Solicitud
@{
    ViewData["Title"] = "Cambiar Estado de Solicitud";
}

<h1>Cambiar Estado de Solicitud</h1>
<form asp-action="ChangeStatus" asp-controller="Solicitudes" method="post">
    @Html.AntiForgeryToken()

    <!--- ListItem de Estado de Solicitud del formulario   -->
    <div class="mb-3 form-group">
        <label asp-for="EstadoSolicitudId" class="form-label">Cambiar Estado</label>
        <select asp-for="EstadoSolicitudId" class="form-control">
            @(ViewBag.Estados.Count == 0 ? "disabled" : "")
            @foreach (var estado in ViewBag.Estados)
            {
                <option value="@estado.Id">@estado.Nombre</option>
            }
        </select>
        <span asp-validation-for="EstadoSolicitudId" class="text-danger"></span>
    </div>

    <!--- Para Lista de Estados   -->
    <div class="mb-3 form-group">
        <label asp-for="EstadoSolicitudId" class="form-label">Estado</label>
        <select class="form-select form-select sm" asp-for="EstadoSolicitudId" asp-items="ViewBag.Estados">
            <option> --- Seleccionar Estado --- </option>
        </select>
        <span asp-validation-for="EstadoSolicitudId" class="text-danger"></span>
    </div>

    <input type="hidden" asp-for="Id" />

    <!---------------  Botones summit y cancelar  ------------->
    <button type="submit" class="btn btn-primary"><i class="bi bi-check-square"></i> Aplicar</button>
    <a class="btn btn-dark" asp-action="Index"><i class="bi bi-x-square"></i> Cancelar</a>

</form>

GestionImpresoras/Views/Solicitudes/Crear.cshtml
@using (Html.BeginForm())
@using GestionImpresoras.Models;
@model Solicitud
@{
        ViewData["Title"] = "Crear nueva Solicitud";
}
@Html.AntiForgeryToken()
<h1>Crear Solicitud</h1>
<h5>Se refiere a las Solicitudes de tóner o repuestos para impresoras utilizadas en la institución </h5>
<hr />
<form asp-action="Crear" asp-controller="Solicitudes" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <!---  Para Lista de Impresoras   -->
    <div class="mb-3 form-group">
        <label asp-for="ImpresoraId" class="form-label">Impresora</label>
        <select class="form-select form-select sm" asp-for="ImpresoraId" asp-items="ViewBag.ImpresoraId">
            <option> --- Seleccionar Impresora --- </option>
        </select>
        <span asp-validation-for="ImpresoraId" class="text-danger"></span>
    </div>
    <!--- Para Lista de Estado de Solicitud   -->
    <div class="mb-3 form-group">
        <label asp-for="EstadoSolicitudId" class="form-label">Estado</label>
        <select class="form-select form-select sm" asp-for="EstadoSolicitudId" asp-items="ViewBag.EstadoSolicitudId">
            <option> --- Seleccionar Estado --- </option>
        </select>
        <span asp-validation-for="EstadoSolicitudId" class="text-danger"></span>
    </div>
    <!--- Para Lista de Color Solicitado   -->
    <div class="mb-3 form-group">
        <label asp-for="ColorId" class="form-label">Color</label>
        <select class="form-select form-select sm" asp-for="ColorId" asp-items="ViewBag.ColorId">
            <option> --- Seleccionar Color --- </option>
        </select>
        <span asp-validation-for="ColorId" class="text-danger"></span>
    </div>
    <!---  Para Lista de Fecha de Solicitud   -->
    <div class="mb-3 form-group">
        <label asp-for="FechaSolicitud" class="form-label">Fecha Solicitud</label>
        <input type="date" asp-for="FechaSolicitud" class="form-control" />
        <span asp-validation-for="FechaSolicitud" class="text-danger"></span>
    </div>
    <!--- Para Solicitante   -->
    <div class="mb-3 form-group">
        <label asp-for="Solicitante" class="form-label">Solicitante</label>
        <input type="text" asp-for="Solicitante" class="form-control" placeholder="Ingrese la persona Solicitante" />
        <span asp-validation-for="Solicitante" class="text-danger"></span>
    </div>
    <!--- Para Lista de Medio Solicitado   -->
    <div class="mb-3 form-group">
        <label asp-for="MedioId" class="form-label">Medio de Solicitud</label>
        <select class="form-select form-select sm" asp-for="MedioId" asp-items="ViewBag.MedioId">
            <option> --- Seleccionar Medio --- </option>
        </select>
        <span asp-validation-for="MedioId " class="text-danger"></span>
    </div>
    <!--- Para Detalles  -->
    <div class="mb-3 form-group">
        <label asp-for="Detalle" class="form-label">Detalles de la solicitud</label>
        <textarea asp-for="Detalle" class="form-control" id="detalle-input" placeholder="Ingrese los Detalles de la solicitud"></textarea>
        <span asp-validation-for="Detalle" class="text-danger"></span>
    </div>
    <!--- Para Imagenes de documentación  -->
    <div class="mb-3 form-group">
        <label asp-for="UrlImagen" class="form-label">Imagenes para documentar</label>
        <input type="file" asp-for="UrlImagen" class="form-control" name="UrlImagen" id="UpImagen" placeholder="Ingrese la imagen soporte" accept="image/*" />
        <span asp-validation-for="UrlImagen" class="text-danger"></span>
    </div>
    <!---------------  Botones summit y cancelar  ------------->
    <button type="submit" class="btn btn-primary"><i class="bi bi-pencil-fill"></i> Enviar</button>
    <a class="btn btn-secondary" asp-action="Index"><i class="bi bi-backspace"></i> Cancelar</a>
</form>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
<!---------------  Codigo para utilizar editor de codigo  TinyMCE  ------------->
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
<script>
    tinymce.init({
        selector: '#detalle-input',
        plugins: 'lists',
        menubar: 'file edit format'
    });
</script>
<script>
    tinymce.init({
        selector: 'textarea',
        plugins: 'lists',
        menubar: 'file edit format'
    });
</script>

<style>
    .validation-summary-errors {
        display: none;
    }
</style>
}

GestionImpresoras/Views/Solicitudes/Create.cshtml
@using (Html.BeginForm())
@using GestionImpresoras.Models;
@model Solicitud
@{
        ViewData["Title"] = "Crear nueva Solicitud";
}
@Html.AntiForgeryToken()
<h1>Crear Solicitud</h1>
<h5>Se refiere a las Solicitudes de tóner o repuestos para impresoras utilizadas en la institución </h5>
<hr />
<form asp-action="Create" asp-controller="Solicitudes" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <!---  Para Lista de Impresoras   -->
    <div class="mb-3 form-group">
        <label asp-for="ImpresoraId " class="form-label">Impresora</label>
        <select class="form-select form-select sm" asp-for="ImpresoraId" asp-items="ViewBag.ImpresoraId">
            <option> --- Seleccionar Impresora --- </option>
        </select>
        <span asp-validation-for="ImpresoraId" class="text-danger"></span>
    </div>
    <!--- Para Lista de Estado de Solicitud   -->
    <div class="mb-3 form-group">
        <label asp-for="EstadoSolicitudId" class="form-label">Estado</label>
        <select class="form-select form-select sm" asp-for="EstadoSolicitudId" asp-items="ViewBag.EstadoSolicitudId">
            <option> --- Seleccionar Estado --- </option>
        </select>
        <span asp-validation-for="EstadoSolicitudId" class="text-danger"></span>
    </div>
    <!--- Para Lista de Color Solicitado   -->
    <div class="mb-3 form-group">
        <label asp-for="ColorId" class="form-label">Color</label>
        <select class="form-select form-select sm" asp-for="ColorId" asp-items="ViewBag.ColorId">
            <option> --- Seleccionar Color --- </option>
        </select>
        <span asp-validation-for="ColorId" class="text-danger"></span>
    </div>
    <!---  Para Lista de Fecha de Solicitud   -->
    <div class="mb-3 form-group">
        <label asp-for="FechaSolicitud" class="form-label">Fecha Solicitud</label>
        <input type="date" asp-for="FechaSolicitud" class="form-control" />
        <span asp-validation-for="FechaSolicitud" class="text-danger"></span>
    </div>
    <!--- Para Solicitante   -->
    <div class="mb-3 form-group">
        <label asp-for="Solicitante" class="form-label">Solicitante</label>
        <input type="text" asp-for="Solicitante" class="form-control" placeholder="Ingrese la persona Solicitante" />
        <span asp-validation-for="Solicitante" class="text-danger"></span>
    </div>
    <!--- Para Email   -->
    <div class="mb-3 form-group">
        <label asp-for="Email" class="form-label">Solicitante</label>
        <input type="text" asp-for="Email" class="form-control" placeholder="Ingrese el correo del Solicitante" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <!--- Para Lista de Medio Solicitado   -->
    <div class="mb-3 form-group">
        <label asp-for="MedioId" class="form-label">Medio de Solicitud</label>
        <select class="form-select form-select sm" asp-for="MedioId" asp-items="ViewBag.MedioId">
            <option> --- Seleccionar Medio --- </option>
        </select>
        <span asp-validation-for="MedioId " class="text-danger"></span>
    </div>
    <!--- Para Detalles  -->
    <div class="mb-3 form-group">
        <label asp-for="Detalle" class="form-label">Detalles de la solicitud</label>
        <textarea asp-for="Detalle" class="form-control" id="detalle-input" placeholder="Ingrese los Detalles de la solicitud"></textarea>
        <span asp-validation-for="Detalle" class="text-danger"></span>
    </div>
    <!--- Para Imagenes de documentación  -->
    <div class="mb-3 form-group">
        <label asp-for="UrlImagen" class="form-label">Imagenes para documentar</label>
        <input type="file" asp-for="UrlImagen" class="form-control" name="UrlImagen" id="UpImagen" placeholder="Ingrese la imagen soporte" accept="image/*" />
        <span asp-validation-for="UrlImagen" class="text-danger"></span>
    </div>
    <!---------------  Botones summit y cancelar  ------------->
    <button type="submit" class="btn btn-primary"><i class="bi bi-check-square"></i> Aplicar</button>
    <a class="btn btn-secondary" asp-action="Index"><i class="bi bi-backspace"></i> Cancelar</a>
</form>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
<!---------------  Codigo para utilizar editor de codigo  TinyMCE  ------------->
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
<script>
    tinymce.init({
        selector: '#detalle-input',
        plugins: 'lists',
        menubar: 'file edit format'
    });
</script>
<script>
    tinymce.init({
        selector: 'textarea',
        plugins: 'lists',
        menubar: 'file edit format'
    });
</script>

<style>
    .validation-summary-errors {
        display: none;
    }
</style>
}